# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e022e49c2a6a1d92895f5578d195aa1bc22c84565e1761fa4cd081c22e822b49c2cb0151b2b5c584e31c243fe8c553944c026225eeb2530c602531b6438855b

test:
  secret_key_base: df54623bb86d4ffb959069200b3c37c1fa449982feaaf1aa2cc22d6eaa0c9a0b24f899631636a9fea51c88272877847193c817f7377262abaa9fe1aa51a88031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
